name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Use pnpm instead of npm
      - name: Install pnpm
        run: npm install -g pnpm@6

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm # Use pnpm cache

      - name: Install dependencies
        run: pnpm install

      - name: build
        env:
          BASE_PATH: '/Portfolio'
        run: |
          pnpm run build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: build/

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
